CREATE TABLE GOOGLE_TRENDS.GOOGLE_TRENDS_RAW
(
    KEYWORD      VARCHAR(512) NOT NULL,
    SET_ID       NUMBER       NOT NULL,
    DATE         DATE         NOT NULL,
    GOOGLE_TRENDS_CATE         VARCHAR(64)  NOT NULL,
    GEO          VARCHAR(32)  NOT NULL,
    TIMEFRAME    VARCHAR(32)  NOT NULL,
    GPROP        VARCHAR(32),
    ANCHOR       VARCHAR(64),
    VALUE        DOUBLE       NOT NULL,
    ANCHOR_VALUE DOUBLE
);

CREATE TABLE GOOGLE_TRENDS._LOOKUP_RETAILER_ENTITY_MAPPING
(
    RETAILER_CODE  NUMBER,
    RETAILER_NAME  VARCHAR,
    ENCODED_TERM   VARCHAR,
    KEYWORD        VARCHAR,
    TYPE_OF_ENTITY VARCHAR
);

CREATE TABLE GOOGLE_TRENDS._LOOKUP_SET
(
    ID             NUMBER,
    CATE           VARCHAR,
    GEO            VARCHAR,
    TIMEFRAME      VARCHAR,
    GPROP          VARCHAR,
    DEFAULT_ANCHOR VARCHAR
);

CREATE TABLE GOOGLE_TRENDS._LOOKUP_SET_KEYWORD
(
    SET_ID                           NUMBER  NOT NULL,
    KEYWORD                          VARCHAR NOT NULL,
    LOCKED                           NUMBER(1) DEFAULT 0,
    NO_DATA                          NUMBER(1) DEFAULT 0,
    INDIVIDUAL_DONE                  NUMBER(1) DEFAULT 0,
    PAIRED_DONE                      NUMBER(1) DEFAULT 0,
    TRY_TIMES                        NUMBER    DEFAULT 0,
    ANCHOR                           VARCHAR,
    ANCHOR_TRY_TIMES                 NUMBER    DEFAULT 0,
    MAX_KEYWORD_VALUE                NUMBER(10, 4),
    MAX_ANCHOR_VALUE                 NUMBER(10, 4),
    KEYWORD_ANCHOR_MAX_RATIO         NUMBER(38, 10),
    KEYWORD_DEFAULT_ANCHOR_MAX_RATIO NUMBER(38, 10),
    AVG_KEYWORD_VALUE                NUMBER(10, 4),
    AVG_ANCHOR_VALUE                 NUMBER(10, 4),
    KEYWORD_ANCHOR_AVG_RATIO         NUMBER(38, 10),
    KEYWORD_DEFAULT_ANCHOR_AVG_RATIO NUMBER(38, 10),
    PREFERRED_ANCHOR_INDEX           NUMBER,
    LOWER_BOUND_ANCHOR_INDEX         NUMBER    DEFAULT -999999999,
    UPPER_BOUND_ANCHOR_INDEX         NUMBER    DEFAULT 999999999,
    CONSTRAINT _LOOKUP_SET_KEYWORD_PK
        PRIMARY KEY (SET_ID, KEYWORD)
);
